name: Zip Slip PoC

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  zip-slip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: listendev/action@v0.11
        with:
          jwt: ${{ secrets.LS1 }}
          ci: only
      - name: Install dependencies
        run: npm install .

      - name: Run Zip Slip exploit
        run: node index.js

      - name: Check /tmp directory contents
        run: ls -al /tmp/

      - name: Check /tmp/safe directory contents
        run: ls -al /tmp/safe/
