name: Zip Slip PoC

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  zip-slip:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install .

      # Step 4: Run the Zip Slip exploit
      - name: Run Zip Slip exploit
        run: node index.js

      # Step 5: Verify if the evil.txt was extracted outside /tmp/safe
      - name: Check /tmp directory contents
        run: ls -al /tmp/

      # Step 6: Verify the /tmp/safe directory contents
      - name: Check /tmp/safe directory contents
        run: ls -al /tmp/safe/
